spring:
  application:
    name: akalj


management:
  endpoint:
    health:
      show-details: always
  server:
    port: 8081

akalj:
  garbage-types:
    BIO:
      - Bioabfall
    RESTMUELL:
      - Restmüll
    PAPIER:
      - Papier
    WERTSTOFF:
      - Wertstoff

