spring:
  application:
    name: akalj
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASS}
    username: ${REDIS_USER:default}


management:
  endpoint:
    health:
      show-details: always
  server:
    port: 8081

akalj:
  baseUrl: "https://web4.karlsruhe.de/service/abfall/akal/akal_2024.php"
  secure: false
  garbage-types:
    BIO:
      - Bioabfall
    RESTMUELL:
      - Restmüll
    PAPIER:
      - Papier
    WERTSTOFF:
      - Wertstoff

